In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pandas as pd
import numpy as np

In [ ]:
X,y = load_iris(return_X_y=True, as_frame=True)

In [ ]:
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [ ]:
# Split dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=11)

In [ ]:
X_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
58                 6.6               2.9                4.6               1.3
35                 5.0               3.2                1.2               0.2
130                7.4               2.8                6.1               1.9
46                 5.1               3.8                1.6               0.2
..                 ...               ...                ...               ...
76                 6.8               2.8                4.8               1.4
13                 4.3               3.0                1.1               0.1
81                 5.5               2.4                3.7               1.0
91                 6.1               3.0                4.6               1.4
80                 5.5               2.4                3.8               1.1

[105 rows x 4 columns]

In [ ]:
X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
112                6.8               3.0                5.5               2.1
145                6.7               3.0                5.2               2.3
133                6.3               2.8                5.1               1.5
56                 6.3               3.3                4.7               1.6
111                6.4               2.7                5.3               1.9
9                  4.9               3.1                1.5               0.1
65                 6.7               3.1                4.4               1.4
15                 5.7               4.4                1.5               0.4
30                 4.8               3.1                1.6               0.2
63                 6.1               2.9                4.7               1.4
119                6.0               2.2                5.0               1.5
62                 6.0               2.2                4.0               1.0
84                 5.4               3.0                4.5               1.5
113                5.7               2.5                5.0               2.0
139                6.9               3.1                5.4               2.1
41                 4.5               2.3                1.3               0.3
103                6.3               2.9                5.6               1.8
66                 5.6               3.0                4.5               1.5
110                6.5               3.2                5.1               2.0
142                5.8               2.7                5.1               1.9
69                 5.6               2.5                3.9               1.1
2                  4.7               3.2                1.3               0.2
22                 4.6               3.6                1.0               0.2
51                 6.4               3.2                4.5               1.5
12                 4.8               3.0                1.4               0.1
11                 4.8               3.4                1.6               0.2
149                5.9               3.0                5.1               1.8
75                 6.6               3.0                4.4               1.4
16                 5.4               3.9                1.3               0.4
85                 6.0               3.4                4.5               1.6
0                  5.1               3.5                1.4               0.2
120                6.9               3.2                5.7               2.3
122                7.7               2.8                6.7               2.0
49                 5.0               3.3                1.4               0.2
29                 4.7               3.2                1.6               0.2
118                7.7               2.6                6.9               2.3
105                7.6               3.0                6.6               2.1
77                 6.7               3.0                5.0               1.7
36                 5.5               3.5                1.3               0.2
83                 6.0               2.7                5.1               1.6
60                 5.0               2.0                3.5               1.0
131                7.9               3.8                6.4               2.0
6                  4.6               3.4                1.4               0.3
52                 6.9               3.1                4.9               1.5
104                6.5               3.0                5.8               2.2

In [ ]:
y_train

98     1
58     1
35     0
130    2
46     0
      ..
76     1
13     0
81     1
91     1
80     1
Name: target, Length: 105, dtype: int64

In [ ]:
y_test

112    2
145    2
133    2
56     1
111    2
9      0
65     1
15     0
30     0
63     1
119    2
62     1
84     1
113    2
139    2
41     0
103    2
66     1
110    2
142    2
69     1
2      0
22     0
51     1
12     0
11     0
149    2
75     1
16     0
85     1
0      0
120    2
122    2
49     0
29     0
118    2
105    2
77     1
36     0
83     1
60     1
131    2
6      0
52     1
104    2
Name: target, dtype: int64

In [ ]:
# Multiclass logistic regression model
model = LogisticRegression()

In [ ]:
model

LogisticRegression()

In [ ]:
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
# Predictions
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 1,
       2])

In [ ]:
y_test

112    2
145    2
133    2
56     1
111    2
9      0
65     1
15     0
30     0
63     1
119    2
62     1
84     1
113    2
139    2
41     0
103    2
66     1
110    2
142    2
69     1
2      0
22     0
51     1
12     0
11     0
149    2
75     1
16     0
85     1
0      0
120    2
122    2
49     0
29     0
118    2
105    2
77     1
36     0
83     1
60     1
131    2
6      0
52     1
104    2
Name: target, dtype: int64

In [ ]:
y_pred

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 1,
       2])

In [ ]:
# Evaluation metrics
conf_matrix = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print('Confusion Matrix:\n', conf_matrix)
print('\nAccuracy:', accuracy)
print('\nClassification Report:\n', report)

Confusion Matrix:
 [[14  0  0]
 [ 0 12  2]
 [ 0  1 16]]

Accuracy: 0.9333333333333333

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.92      0.86      0.89        14
           2       0.89      0.94      0.91        17

    accuracy                           0.93        45
   macro avg       0.94      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [ ]:
# Import pickle for saving and loading the model
import pickle

# Filepath for saving the model
pickle_file = 'logistic_regression_multiclass.pkl'

# Save the trained model to a pickle file
with open(pickle_file, 'wb') as file:
    pickle.dump(model, file)

print(f'Model saved to {pickle_file}')

Model saved to logistic_regression_multiclass.pkl

In [ ]:
# Load the model from the pickle file
with open(pickle_file, 'rb') as file:
    loaded_model = pickle.load(file)

# Test the loaded model with predictions
y_pred_loaded = loaded_model.predict(X_test)
print(y_pred_loaded)

[2 2 2 1 2 0 1 0 0 1 1 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1 0 2 2 0 0 2 2
 2 0 2 1 2 0 1 2]

In [ ]:
y_pred_loaded

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 1,
       2])

In [ ]:
list(y_test)

[2,
 2,
 2,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 2,
 2,
 1,
 0,
 1,
 1,
 2,
 0,
 1,
 2]

In [ ]:
y_pred_loaded = loaded_model.predict([[6.1,2.8,4.7,1.2]])
print(y_pred_loaded)

[1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
112                6.8               3.0                5.5               2.1
145                6.7               3.0                5.2               2.3
133                6.3               2.8                5.1               1.5
56                 6.3               3.3                4.7               1.6
111                6.4               2.7                5.3               1.9
9                  4.9               3.1                1.5               0.1
65                 6.7               3.1                4.4               1.4
15                 5.7               4.4                1.5               0.4
30                 4.8               3.1                1.6               0.2
63                 6.1               2.9                4.7               1.4
119                6.0               2.2                5.0               1.5
62                 6.0               2.2                4.0               1.0
84                 5.4               3.0                4.5               1.5
113                5.7               2.5                5.0               2.0
139                6.9               3.1                5.4               2.1
41                 4.5               2.3                1.3               0.3
103                6.3               2.9                5.6               1.8
66                 5.6               3.0                4.5               1.5
110                6.5               3.2                5.1               2.0
142                5.8               2.7                5.1               1.9
69                 5.6               2.5                3.9               1.1
2                  4.7               3.2                1.3               0.2
22                 4.6               3.6                1.0               0.2
51                 6.4               3.2                4.5               1.5
12                 4.8               3.0                1.4               0.1
11                 4.8               3.4                1.6               0.2
149                5.9               3.0                5.1               1.8
75                 6.6               3.0                4.4               1.4
16                 5.4               3.9                1.3               0.4
85                 6.0               3.4                4.5               1.6
0                  5.1               3.5                1.4               0.2
120                6.9               3.2                5.7               2.3
122                7.7               2.8                6.7               2.0
49                 5.0               3.3                1.4               0.2
29                 4.7               3.2                1.6               0.2
118                7.7               2.6                6.9               2.3
105                7.6               3.0                6.6               2.1
77                 6.7               3.0                5.0               1.7
36                 5.5               3.5                1.3               0.2
83                 6.0               2.7                5.1               1.6
60                 5.0               2.0                3.5               1.0
131                7.9               3.8                6.4               2.0
6                  4.6               3.4                1.4               0.3
52                 6.9               3.1                4.9               1.5
104                6.5               3.0                5.8               2.2

In [ ]:
print(loaded_model.predict([[4.9,2.5,4.5,1.7]]))

In [ ]:
y_pred_loaded = loaded_model.predict([[5.4,3.7,1.5,0.2]])
print(y_pred_loaded)

In [ ]:
y_test